<?php
/**
 * Created by PhpStorm.
 * User: AHMAD
 * Date: 08/04/2016
 * Time: 21:10
 */

namespace app\components;


use yii\web\Controller;

class MyController extends  Controller
{
    public function init()
    {
        $this->layout = 'main';
        parent::init(); // TODO: Change the autogenerated stub

    }
}